<!DOCTYPE html>
<html lang="en-US">
<head>
    <meta charset='utf-8'>
    <meta http-equiv="X-UA-Compatible" content="chrome=1">
    <link href='https://fonts.googleapis.com/css?family=Chivo:900' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="/kbarchive/assets/css/style.css?v=d2057ae472d963fbdcbf65805f43123bccb709dc">
    <link rel="stylesheet" type="text/css" href="/kbarchive/assets/css/print.css" media="print">
    <!--[if lt IE 9]>
    <script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Begin Jekyll SEO tag v2.5.0 -->
<title>Q98601: HOWTO: Handle Exceptions That Occur in Exception Processing | KnowledgeBase Archive</title>
<meta name="generator" content="Jekyll v3.8.5" />
<meta property="og:title" content="Q98601: HOWTO: Handle Exceptions That Occur in Exception Processing" />
<meta property="og:locale" content="en_US" />
<meta name="description" content="An Archive of Early Microsoft KnowledgeBase Articles" />
<meta property="og:description" content="An Archive of Early Microsoft KnowledgeBase Articles" />
<link rel="canonical" href="http://jeffpar.github.io/kbarchive/kb/098/Q98601/" />
<meta property="og:url" content="http://jeffpar.github.io/kbarchive/kb/098/Q98601/" />
<meta property="og:site_name" content="KnowledgeBase Archive" />
<script type="application/ld+json">
{"headline":"Q98601: HOWTO: Handle Exceptions That Occur in Exception Processing","url":"http://jeffpar.github.io/kbarchive/kb/098/Q98601/","description":"An Archive of Early Microsoft KnowledgeBase Articles","@type":"WebPage","@context":"http://schema.org"}</script>
<!-- End Jekyll SEO tag -->

</head>

<body>
<div id="container">
    <div class="inner">

        <header>
            <h1><a href="/kbarchive">KnowledgeBase Archive</a></h1>
            <h2>An Archive of Early Microsoft KnowledgeBase Articles</h2>
        </header>
        <section id="downloads" class="clearfix">
            
            
            <a href="https://github.com/jeffpar/kbarchive" id="view-on-github" class="button"><span>View on GitHub</span></a>
            
        </section>
        <hr>
        <section id="main_content">
                <div>
        <h2 id="q98601-howto-handle-exceptions-that-occur-in-exception-processing">Q98601: HOWTO: Handle Exceptions That Occur in Exception Processing</h2>

<div class="highlighter-rouge"><div class="highlight"><pre class="highlight"><code>Article: Q98601
Product(s): Microsoft C Compiler
Version(s): winnt:1.0,2.0,2.1,4.0
Operating System(s): 
Keyword(s): kbnokeyword kbMFC kbVC100 kbVC150 kbVC200 kbVC400 kbGrpDSMFCATL kbExceptHandMFC kbExcep
Last Modified: 31-JUL-2001

-------------------------------------------------------------------------------
The information in this article applies to:

- The Microsoft Foundation Classes (MFC), used with:
   - Microsoft C/C++ for MS-DOS, version 7.0 
   - Microsoft Visual C++ for Windows, 16-bit edition, versions 1.0, 1.5, 1.51, 1.52 
   - Microsoft Visual C++, 32-bit Editions, versions 1.0, 2.0, 2.1, 4.0 
-------------------------------------------------------------------------------

SUMMARY
=======

The Microsoft Foundation Classes stores a pointer to the current application
exception in a global variable. If the application causes the exception to be
thrown while the application is processing another exception, the original
exception object is deleted. If the application needs to track the original
exception, then it must store the information in that exception object in a
separate variable. The application can use this information to throw the
original exception again to pass the exception to the next exception handling
block.

MORE INFORMATION
================

If an application is handling an exception in a CATCH block, and a new exception
is thrown, the Microsoft Foundation Class (MFC) library deletes the original
exception. If the CATCH block uses information about the original exception
after the second exception, or if the CATCH block calls the THROW_LAST macro and
another exception could occur in the CATCH block, the application should store
information about the original exception at the beginning of the CATCH block.
When the application requires information about the original exception, retrieve
the data from the variables instead of from the exception object. To pass the
exception to the next exception handling block, call the THROW macro to create a
new exception instead of using the THROW_LAST macro to use the current
exception. The following pseudo-code demonstrates this technique:

     TRY
        {
        // Start a large TRY block to catch any archive exceptions
        // that occur while archiving.

        // Start archiving process here.

        TRY
           {
           // In this TRY block, perform some action that might
           // cause a CArchiveException to be thrown.

           if (a recoverable archive error has occurred)
               AfxThrowArchiveException(CArchiveException::generic);
           }
        CATCH(CArchiveException, ArchEx)
           {
           // Save information about exception for later.
           int nCause = ArchEx-&gt;m_cause;

           TRY
              {
              // To process the CArchiveException, the application
              // allocates memory and a CMemoryException may occur.
              }
           CATCH(CMemoryException, MemEx)
              {
              // Process the memory exception.
              }
           END_CATCH

           // At this point, the ArchEx object is not valid if the
           // CMemoryException occurred. Therefore, use the nCause
           // variable to retrieve information about the exception.

           // Throw the archive exception again. (THROW_LAST does
           // not produce correct results if CMemoryException occurred.
           if (need to pass up to next exception block)
              AfxThrowArchiveException(nCause);
           }
        END_CATCH

     CATCH(CArchiveException, ArchEx)
        {
        // handle the archive exception
        }
     END_CATCH

NOTE: In the versions of MFC included with Visual C++ 32-bit Edition, versions
2.0 and above, the current exception is stored on a per-thread basis. However,
the technique described in this article still applies.

Additional query words: nested exceptions

======================================================================
Keywords          : kbnokeyword kbMFC kbVC100 kbVC150 kbVC200 kbVC400 kbGrpDSMFCATL kbExceptHandMFC kbExceptHandling 
Technology        : kbAudDeveloper kbMFC
Version           : winnt:1.0,2.0,2.1,4.0
Issue type        : kbhowto

=============================================================================
</code></pre></div></div>


        <p>
            THE INFORMATION PROVIDED IN THE MICROSOFT KNOWLEDGE BASE IS
            PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND.  MICROSOFT DISCLAIMS
            ALL WARRANTIES, EITHER EXPRESS OR IMPLIED, INCLUDING THE WARRANTIES
            OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.  IN NO
            EVENT SHALL MICROSOFT CORPORATION OR ITS SUPPLIERS BE LIABLE FOR
            ANY DAMAGES WHATSOEVER INCLUDING DIRECT, INDIRECT, INCIDENTAL,
            CONSEQUENTIAL, LOSS OF BUSINESS PROFITS OR SPECIAL DAMAGES, EVEN IF
            MICROSOFT CORPORATION OR ITS SUPPLIERS HAVE BEEN ADVISED OF THE
            POSSIBILITY OF SUCH DAMAGES.  SOME STATES DO NOT ALLOW THE EXCLUSION
            OR LIMITATION OF LIABILITY FOR CONSEQUENTIAL OR INCIDENTAL DAMAGES
            SO THE FOREGOING LIMITATION MAY NOT APPLY.
        </p>
        <p>Copyright Microsoft Corporation 1986-2002.</p>
    </div>

        </section>

        <footer>
            
            KnowledgeBase Archive is maintained by <a href="https://www.pcjs.org">PCjs</a>.<br>
            
            This page was generated by <a href="https://pages.github.com">GitHub Pages</a>.
        </footer>

    </div>
</div>


<script type="text/javascript">
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
    ga('create', 'UA-49658648-3', 'auto');
    ga('send', 'pageview');
</script>

</body>
</html>